android.builtInKotlin=false
android.defaults.buildfeatures.resvalues=true
android.dependency.useConstraints=true
android.enableAppCompileTimeRClass=false
android.newDsl=false

android.r8.strictFullModeForKeepRules=false
android.sdk.defaultTargetSdkToCompileSdkIfUnset=false
android.uniquePackageNames=false
android.useAndroidX=true
android.usesSdkInManifest.disallowed=false
org.gradle.configuration-cache=true
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m
android.sync.suppressAgpWarnings=UNSUPPORTED_PROJECT_OPTION_USE,DEPRECATED_DSL,LIBRARY_CONSTRAINTS_SHOULD_BE_DISABLED

android.enableR8.fullMode=true

ANTIGRAVITY_RELEASE_STORE_FILE=release.keystore
ANTIGRAVITY_RELEASE_STORE_PASSWORD=antigravity_release_pass
ANTIGRAVITY_RELEASE_KEY_ALIAS=antigravity
ANTIGRAVITY_RELEASE_KEY_PASSWORD=antigravity_release_pass
